/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hack_com_tantan_JavaUtils */

#ifndef _Included_hack_com_tantan_JavaUtils
#define _Included_hack_com_tantan_JavaUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hack_com_tantan_JavaUtils
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hack_com_tantan_JavaUtils_getString
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
