/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hack_com_tantan_JavaUtils */

#ifndef _Included_hack_com_tantan_JavaUtils
#define _Included_hack_com_tantan_JavaUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hack_com_tantan_JavaUtils
 * Method:    createNetwork
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_hack_com_tantan_JavaUtils_createNetwork
  (JNIEnv *, jobject, jlong);

/*
 * Class:     hack_com_tantan_JavaUtils
 * Method:    init
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_hack_com_tantan_JavaUtils_init
  (JNIEnv *, jobject, jlong);

/*
 * Class:     hack_com_tantan_JavaUtils
 * Method:    uninit
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_hack_com_tantan_JavaUtils_uninit
  (JNIEnv *, jobject, jlong);

/*
 * Class:     hack_com_tantan_JavaUtils
 * Method:    ProbingLostrateAndRTT
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_hack_com_tantan_JavaUtils_ProbingLostrateAndRTT
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     hack_com_tantan_JavaUtils
 * Method:    GetLostrate
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_hack_com_tantan_JavaUtils_GetLossrate
  (JNIEnv *, jobject, jlong);

/*
 * Class:     hack_com_tantan_JavaUtils
 * Method:    GetRTT
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_hack_com_tantan_JavaUtils_GetRTT
  (JNIEnv *, jobject, jlong);

/*
 * Class:     hack_com_tantan_JavaUtils
 * Method:    ProbingUpBw
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_hack_com_tantan_JavaUtils_ProbingUpBw
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     hack_com_tantan_JavaUtils
 * Method:    GetUpBw
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_hack_com_tantan_JavaUtils_GetUpBw
  (JNIEnv *, jobject, jlong);

/*
 * Class:     hack_com_tantan_JavaUtils
 * Method:    ProbingDownBw
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_hack_com_tantan_JavaUtils_ProbingDownBw
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     hack_com_tantan_JavaUtils
 * Method:    GetDownBw
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_hack_com_tantan_JavaUtils_GetDownBw
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
